import type { Project } from "~/types/projects";

export default [
  {
    id: "1",
    title: "Casa Boierului Comaniciu",
    slug: "casa-boierului-comaniciu",
    meta: {
      id: "BV-II-m-B-21165 “Casa Comăniciu”",
      function: ["Cultural-educativa", "Rezidențial (Unifamilial)"],
      year: "2020-2023",
      location: "Veneția de Jos, Brașov",
      colaborators: [
        "Arh. M. Iliescu - specialist MC",
        "Arh. Raluca Maria Olaru",
        "Ing. Bodor Csaba - expert MC",
        "rest. Ioana Cristina Munteanu-Zărnescu - expert MC",
      ],
      technical_data: {
        cd: "250 mp",
      },
    },
    type: ["Restaurare"],
    status: "Finalizat",
    description: `Proiectul a inclus restaurarea casei Comănici, monument istoric din 2019, și extinderea cu un nou corp pe locul fostei șuri. Clădirea, afectată de tasări, umiditate și zidărie defectuoasă, a fost consolidată prin refacerea tencuielilor, zidăriei, pardoselilor și șarpantei. Analizele au datat elementele de lemn în jurul anului 1830.`,
    image: {
      src: "/images/projects/venetia/venetia-1.jpg",
    },
    gallery: [
      {
        src: "/images/projects/venetia/venetia-1.jpg",
        alt: "Sample landscape",
      },
      {
        src: "/images/projects/venetia/venetia-2.jpg",
        alt: "Sample landscape",
      },
      {
        src: "/images/projects/venetia/venetia-3.jpg",
        alt: "Sample landscape",
      },
      {
        src: "/images/projects/venetia/venetia-4.jpg",
        alt: "Sample landscape",
      },
      {
        src: "/images/projects/venetia/venetia-5.jpg",
        alt: "Sample landscape",
      },
      {
        src: "/images/projects/venetia/venetia-6.jpg",
        alt: "Sample landscape",
      },
    ],
    hidden: false,
  },
  {
    id: "2",
    title: "Constantin Brâncoveanu nr.8",
    slug: "constantin-brancoveanu-nr-8",
    meta: {
      id: "BV-II-m-B-11369 “Casă”",
      function: ["Comerciala"],
      year: "",
      location: "Brașov, jud. Brașov",
      colaborators: [
        "Arh. M. Iliescu - expert MC",
        "Arh. Raluca Maria Olaru",
        "Ing. Bodor Csaba - expert MC",
        "S.C. ArenaCAD S.R.L.- scanare Laser",
        "rest. Ioana Cristina Munteanu Zărnescu - expert MC, cercetare de parament",
      ],
      technical_data: {
        sd: "1388 mp",
      },
    },
    type: ["Restaurare"],
    status: "In Desfășurare",
    description: `Clădirea în U, datată 1800, cu fațadă neoclasică modificată în sec. XIX și galerie adăugată în 1900, va fi restaurată prin decopertarea tencuielilor deteriorate, verificarea și înlocuirea planșeelor din lemn unde e necesar, refacerea pardoselii la subsol, redeschiderea aerisirilor, refacerea pavajului în gang și curte, restaurarea cornișelor, brâielor, ancadramentelor și galeriei din lemn, precum și revizuirea acoperișului.`,
    image: {
      src: "/images/projects/brancoveanu-8/brancoveanu-8-1.jpg",
    },
    gallery: [],
    hidden: false,
  },
  {
    id: "3",
    title: "Biserica «Sf. Treime» Ghimbav",
    slug: "biserica-sf-treime-ghimbav",
    meta: {
      id: "BV-II-m-B-11701 “Biserica Sf. Treime”",
      function: ["Lacaş de cult"],
      year: "",
      location: "Ghimbav, jud. Brașov",
      colaborators: [
        "Arh. Marina Iliescu - expert MC",
        "Arh. Ioana-Mădălina Bârsășteanu",
        "Ist. artă Ileana Burnichioiu - specialist MC",
        "Ing. Bodor Csaba - expert MC",
        "rest. Maria Dumbrăvician - specialist MC",
      ],
      technical_data: {
        sd: "170 mp",
      },
    },
    type: ["Restaurare"],
    status: "In Desfășurare",
    description: `Construcția trilobată, definitivată între 1780-1805 și completată ulterior cu contraforturi, este o realizare modestă ca dimensiuni și execuție, vizibilă după decopertările din 2013-2017. Exteriorul are o elevație simplă, cornișă de tencuială, acoperiș în două ape cu țiglă ceramică și turn clopotniță cu coif octogonal. Nișele superioare, cândva pictate, au fost repictate recent. Intervențiile propuse vizează corectarea deficiențelor și asigurarea funcționării corespunzătoare a bisericii.`,
    image: {
      src: "",
    },
    gallery: [],
    hidden: false,
  },
  {
    id: "4",
    title: "Constantin Brâncoveanu nr.42",
    slug: "constantin-brancoveanu-nr-42",
    meta: {
      id: "BV-II-m-B-11381 Casă",
      function: ["Rezidențial (Unifamilial)"],
      year: "",
      location: "Brașov, jud. Brașov",
      colaborators: [
        "Arh. Alexandra Stoica - specialist MC",
        "Arh. Silvia Creoșteanu",
      ],
      technical_data: {
        sd: "",
      },
    },
    type: ["Restaurare"],
    status: "In Desfășurare",
    description: `Proiectul vizează consolidarea, amenajarea și extinderea locuinței situate la Constantin Brâncoveanu nr.42.`,
    image: {
      src: "/images/projects/brancoveanu-42/brancoveanu-42-1.jpg",
    },
    gallery: [],
    hidden: false,
  },
  {
    id: "5",
    title: "Castelului nr.53",
    slug: "castelului-nr-53",
    meta: {
      id: "BV-II-m-B-11353 “Casă”",
      function: ["Rezidențial (Unifamilial)"],
      year: "",
      location: "Brașov, jud. Brașov",
      colaborators: ["Arh. Marina Iliescu - specialist MC"],
      technical_data: {
        sd: "",
      },
    },
    type: ["Restaurare"],
    status: "In Desfășurare",
    description: ``,
    image: {
      src: "/images/projects/castelului-53/castelului-53-1.jpg",
    },
    gallery: [],
    hidden: false,
  },
  {
    id: "6",
    title: "Casa Negustorilor",
    slug: "casa-negustorilor",
    meta: {
      id: "BV-II-m-A-11573 “Casa Negustorilor (Kaufhaus)”",
      function: "Restaurant",
      year: "",
      location: "Brașov, jud. Brașov",
      colaborators: [
        "Arh. Alexandra Stoica - specialist MC",
        "Arh. Eleonora Diosan",
      ],
      technical_data: {
        sd: "",
      },
    },
    type: ["Restaurare"],
    status: "In Desfășurare",
    description: ``,
    image: {
      src: "",
    },
    gallery: [],
    hidden: false,
  },
  {
    id: "7",
    title: "Mureșenilor nr.9",
    slug: "muresenilor-nr-9",
    meta: {
      id: "BV-II-m-A-11467 “Casa Schobeln”",
      function: "Cazare",
      year: "",
      location: "Brașov, jud. Brașov",
      colaborators: ["Arh. Marina Iliescu - specialist MC"],
      technical_data: {
        sd: "",
      },
    },
    type: ["Restaurare", "Design interior"],
    status: "In Desfășurare",
    description: `Proiectul vizează reabilitarea și amenajarea locuinței situate la Mureșenilor nr.9.`,
    image: {
      src: "",
    },
    gallery: [],
    hidden: false,
  },
  {
    id: "8",
    title: "Postăvarului nr.66",
    slug: "postavarului-nr-66",
    meta: {
      id: "BV-II-m-B-11529 “Casă”",
      function: "",
      year: "",
      location: "Brașov, jud. Brașov",
      colaborators: [
        "Arh. Marina Iliescu - specialist MC",
        "Arh. Ioana-Mădălina Bârsășteanu",
      ],
      technical_data: {
        sd: "",
      },
    },
    type: ["Restaurare"],
    status: "In Desfășurare",
    description: ``,
    image: {
      src: "",
    },
    gallery: [],
    hidden: false,
  },
  {
    id: "9",
    title: "Michael Weiss nr.10",
    slug: "michael-weiss-nr-10",
    meta: {
      id: "BV-II-m-B-11594 “Casă”",
      function: "",
      year: "",
      location: "Brașov, jud. Brașov",
      colaborators: [
        "Arh. Marina Iliescu - specialist MC",
        "Arh. Ioana-Mădălina Bârsășteanu",
      ],
      technical_data: {
        sd: "",
      },
    },
    type: ["Restaurare"],
    status: "In Desfășurare",
    description: `Proiectul vizează reabilitarea anvelopei locuinței situate la Michael Weiss nr.10.`,
    image: {
      src: "",
    },
    gallery: [],
    hidden: false,
  },
  {
    id: "10",
    title: "Viscri nr.166",
    slug: "viscri-nr-166",
    meta: {
      id: "Bv-II-s-A-11841",
      function: "Locuință (unifamilialǎ)",
      year: "",
      location: "Viscri, comuna Bunești, jud. Brașov",
      colaborators: [
        "Arh. Alexandra Stoica - specialist MC",
        "Ist. artă Iozefina Postăvaru - specialist MC",
        "Ing. Ștefan Geantă",
        "Arh. Mara-Teodora Catargiu",
      ],
      technical_data: {
        sd: "",
      },
    },
    type: ["Restaurare"],
    status: "In Desfășurare",
    description: `Proiectul vizează restaurarea și extinderea locuinței situate în Situl rural Viscri.`,
    image: {
      src: "",
    },
    gallery: [],
    hidden: false,
  },
  {
    id: "11",
    title: "Alma Vii nr.106",
    slug: "alma-vii-nr-106",
    meta: {
      id: "",
      function: "",
      year: "",
      location: "Alma Vii, jud. Sibiu",
      colaborators: [],
      technical_data: {
        sd: "",
      },
    },
    type: [],
    status: "In Desfășurare",
    description: ``,
    image: {
      src: "",
    },
    gallery: [],
    hidden: false,
  },
  {
    id: "12",
    title: "Alma Vii nr.77",
    slug: "alma-vii-nr-77",
    meta: {
      id: "",
      function: "",
      year: "",
      location: "Alma Vii, jud. Sibiu",
      colaborators: [],
      technical_data: {
        sd: "",
      },
    },
    type: [],
    status: "In Desfășurare",
    description: `Proiectul vizează detalii care nu sunt specificate în prezent.`,
    image: {
      src: "",
    },
    gallery: [],
    hidden: false,
  },
  {
    id: "13",
    title: "Piața Unirii nr.16",
    slug: "piata-unirii-nr-16",
    meta: {
      id: "BV-II-m-B-11529",
      function: "Comercial, Locuinta unifamiliala",
      year: "",
      location: "Brașov, jud. Brașov",
      colaborators: [],
      technical_data: {
        sd: "",
      },
    },
    type: ["Restaurare", "Extindere"],
    status: "In Desfășurare",
    description: `Proiectul vizează reabilitarea și amenajarea locuinței situate la Piața Unirii nr.16.`,
    image: {
      src: "",
    },
    gallery: [],
    hidden: false,
  },
  {
    id: "14",
    title: "Str. Ștefan Ludwig Roth nr.3",
    slug: "stefan-ludwig-roth-nr-3",
    meta: {
      id: "BV-II-m-B-11551",
      function: "",
      year: "",
      location: "Brașov, jud. Brașov",
      colaborators: [
        "Arh. Marina Iliescu - specialist MC",
        "Arh. Horațiu Vasilescu",
      ],
      technical_data: {
        sd: "",
      },
    },
    type: ["Restaurare"],
    status: "In Desfășurare",
    description: `Proiectul vizează reabilitarea anvelopei locuinței situate la Str. Ștefan Ludwig Roth nr.3, incluzând revizuirea tencuielilor, învelitorii și a elementelor decorative.`,
    image: {
      src: "",
    },
    gallery: [],
    hidden: true,
  },
  {
    id: "15",
    title: "Str. Republicii nr.34",
    slug: "str-republicii-nr-34",
    meta: {
      id: "Bv-II-s-A-11295",
      function: "Locuință și spațiu comercial",
      year: "",
      location: "Brașov, jud. Brașov",
      colaborators: [],
      technical_data: {
        sd: "",
      },
    },
    type: ["Restaurare"],
    status: "In Desfășurare",
    description: `Proiectul vizează reabilitarea fațadei și reparațiile învelitorii pentru locuința și spațiul comercial situat la Str. Republicii nr.34.`,
    image: {
      src: "",
    },
    gallery: [],
    hidden: false,
  },
  {
    id: "16",
    title: "Str. Castelului nr.96",
    slug: "str-castelului-nr-96",
    meta: {
      id: "Bv-II-s-A-11295",
      function: "Locuință",
      year: "",
      location: "Brașov, jud. Brașov",
      colaborators: [],
      technical_data: {
        sd: "",
      },
    },
    type: ["Restaurare", "Extindere"],
    status: "In Desfășurare",
    description: `Proiectul vizează restaurarea și extinderea locuinței situate la Str. Castelului nr.96.`,
    image: {
      src: "",
    },
    gallery: [],
    hidden: false,
  },
  {
    id: "17",
    title: "Biserica Evanghelică Hălchiu",
    slug: "biserica-evanghelica-halchiu",
    meta: {
      id: "Bv-II-m-B-11709",
      function: "Lăcaș de cult",
      year: "",
      location: "sat Hălchiu, jud. Brașov",
      colaborators: ["Arh. M. Iliescu"],
      technical_data: {
        sd: "",
      },
    },
    type: ["Restaurare"],
    status: "In Desfășurare",
    description: `Proiectul vizează reparațiile fațadelor Bisericii Evanghelice din Hălchiu, incluzând curățarea și restaurarea elementelor de piatră și tencuială.`,
    image: {
      src: "",
    },
    gallery: [],
    hidden: true,
  },
  {
    id: "18",
    title: "Biserica «Adormirea Maicii Domnului» - Satulung",
    slug: "biserica-adormirea-maicii-domnului-satulung",
    meta: {
      id: "Bv-II-a-B-11806",
      function: "Lăcaș de cult",
      year: "",
      location: "Săcele, jud. Brașov",
      colaborators: [],
      technical_data: {
        sd: "", // No specific data provided
      },
    },
    type: ["Restaurare"],
    status: "In Desfășurare",
    description: `Proiectul vizează reabilitarea fațadelor și a învelitorii Bisericii «Adormirea Maicii Domnului» din Satulung.`,
    image: {
      src: "",
    },
    gallery: [],
    hidden: true,
  },
  {
    id: "19",
    title: "Biserica «Nașterea Maicii Domnului» Zărnești",
    slug: "biserica-nasterea-maicii-domnului-zarnesti",
    meta: {
      id: "Bv-II-m-A-11852",
      function: "Lăcaș de cult",
      year: "",
      location: "Zărnești, jud. Brașov",
      colaborators: [],
      technical_data: {
        sd: "", // No specific data provided
      },
    },
    type: ["Restaurare"],
    status: "In Desfășurare",
    description: `Proiectul vizează reparațiile fațadelor și a învelitorii Bisericii «Nașterea Maicii Domnului» din Zărnești.`,
    image: {
      src: "",
    },
    gallery: [],
    hidden: true,
  },
  {
    id: "20",
    title: "Lungă nr.215",
    slug: "lunga-215",
    meta: {
      id: "",
      function: "Comert, Rezidențial (Colectiv)",
      year: "2020-2025",
      location: "Brașov, jud. Brașov",
      colaborators: [],
      technical_data: {
        sd: "1954 mp",
        investment_value: "1.565.000 euro",
      },
    },
    type: ["Extindere"],
    status: "În desfășurare",
    description: `Proiectul vizează construcția de locuințe și spații comerciale în zona protejată a centrului istoric din Brașov.`,
    image: {
      src: "",
    },
    gallery: [],
    hidden: false,
  },
  {
    id: "21",
    title: "Centrul Cultural Bod",
    slug: "centru-cultural-bod",
    meta: {
      id: "",
      function: "Admi",
      year: "2024-2025",
      location: "Tudor Vladimirescu nr.263, Bod, jud. Brașov",
      colaborators: [],
      technical_data: {
        sd: "1.516 mp",
        investment_value: "1.410.000 euro",
      },
    },
    type: ["Restaurare"],
    status: "Planificare SF",
    description: `Proiectul vizează restaurarea și reabilitarea interioară a centrului cultural și birourilor primăriei din Bod.`,
    image: {
      src: "",
    },
    gallery: [],
    hidden: false,
  },
  {
    id: "22",
    title: "Alma Vii 106",
    slug: "alma-vii-106",
    meta: {
      id: "",
      function: "Cazare",
      year: "2023-2024",
      location: "Alma Vii, jud. Sibiu",
      colaborators: [],
      technical_data: {
        sd: "558 mp",
        investment_value: "200.000 euro",
      },
    },
    type: ["Restaurare"],
    status: "Casă finalizată / anexe în construcție",
    description: `Proiectul vizează restaurarea, reabilitarea, extinderea și reparațiile generale ale locuinței din Alma Vii 106.`,
    image: {
      src: "",
    },
    gallery: [],
    hidden: false,
  },
  {
    id: "23",
    title: "Vlaicu nr.99",
    slug: "vlaicu-99",
    meta: {
      id: "",
      function: "Comercial / Rezidential (unifamilial)",
      year: "2021-2024",
      location: "Aurel Vlaicu nr.99, Brașov, jud. Brașov",
      colaborators: [],
      technical_data: {
        sd: "285 mp",
        investment_value: "300.000 euro",
      },
    },
    type: ["Extindere"],
    status: "Finalizat",
    description: ``,
    image: {
      src: "",
    },
    gallery: [],
    hidden: false,
  },
  {
    id: "24",
    title: "Biserica Sf. Nicolae",
    slug: "biserica-sf-nicolae",
    meta: {
      id: "BV-II-m-A-11816",
      function: "Lăcaș de cult",
      year: "2023-2025",
      location: "Sânpetru, jud. Brașov",
      colaborators: [],
      technical_data: {
        sd: "210 mp",
        investment_value: "780.000 euro",
      },
    },
    type: ["Restaurare"],
    status: "Autorizație de construire obținută",
    description: `Proiectul vizează restaurarea bisericii Sf. Nicolae și construcția unui baptisteriu în Sânpetru.`,
    image: {
      src: "",
    },
    gallery: [],
    hidden: false,
  },
  {
    id: "25",
    title: "NB20",
    slug: "nb20",
    meta: {
      id: "",
      function: "Locuință",
      year: "2021-2024",
      location: "Brașov, jud. Brașov",
      colaborators: [],
      technical_data: {
        sd: "1145 mp",
        investment_value: "1.500.000 euro",
      },
    },
    type: ["Construcție nouă"],
    status: "Finalizat",
    description: `Proiectul vizează construcția de locuințe în zona protejată din Brașov.`,
    image: {
      src: "/images/projects/nb20/nb20-1.jpg",
    },
    gallery: [],
    hidden: false,
  },
] as const as Project[];
