# https://github.com/actions/deploy-pages#usage
name: Contentful - Build on Publish
on:
  workflow_dispatch:
  repository_dispatch:
    types: [publish-event]
  push:
    branches:
      - contentful
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: contentful
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      # Pick your own package manager and build script
      - run: npm install
        # - run: npx nuxt build --preset github_pages
      # - run: NUXT_APP_BASE_URL="/${GITHUB_REPOSITORY##*/}/" npx nuxt build --preset github_pages
      - run: NUXT_APP_BASE_URL="/${GITHUB_REPOSITORY##*/}/" npx nuxt generate --preset github_pages
        env:
          NUXT_PUBLIC_CONTENTFUL_SPACE_ID: ${{ vars.CONTENTFUL_SPACE_ID }}
          NUXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN: ${{ vars.CONTENTFUL_ACCESS_TOKEN }}
          NUXT_PUBLIC_CONTENTFUL_ENVIRONMENT: ${{ vars.CONTENTFUL_ENVIRONMENT }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./.output/public
  # Deployment job
  deploy:
    # Add a dependency to the build job
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    # Deploy to the github_pages environment
    environment:
      name: github_pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Contentful - Build on Publish
        id: deployment
        uses: actions/deploy-pages@v4
